name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'        
    - name: nuget add source
      run: dotnet nuget add source --username DanielBock73 --password '${{ secrets.GITHUB_TOKEN }}' --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DanielBock73/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7      
    - name: Build
      run: |
        dotnet pack -p:Configuration=Release \
                    -p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }}.${{ steps.gitversion.outputs.CommitsSinceVersionSource }} \
                    -p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }}
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    - name: Package the project
      run:  dotnet pack --configuration Release
    - name: Deployment the package
      env:
        GITHUB_PAT_NUGET: ${{ secrets.GITHUB_PAT_NUGET }}
      run: dotnet nuget push "src/Hilscher.NetIdent/bin/Release/*.nupkg" --api-key "$GITHUB_PAT_NUGET" --source github
